version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
      - image: redis:3.0.504
      - image: circleci/mysql:5.7.22
        environment:
          MYSQL_DATABASE: 'dddpractice'
          MYSQL_USER: 'dddpractice'
          MYSQL_ROOT_PASSWORD: 'cojedJsji822Kkk'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: gradle dependencies
      - run:
          name: ビルドの実施
          command: gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle.kts" }}

      - run:
          name: テストの実施
          command: gradle test
      - run:
          name: SonarCloudの分析
          command: gradle build sonarqube
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
