version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    working_directory: ~/repo
    steps:
      - checkout
      # 依存関係をダウンロードしてキャシュする
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: gradle dependencies
      - run:
          name: ビルドの実施
          command: gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
      - run:
          name: テストの実施
          command: gradle test